# Generated by Django 3.2 on 2022-01-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TiposExamen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('id_centro', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.centros')),
                ('id_ciudad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ciudades')),
                ('id_departamento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos')),
                ('id_especialidad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades')),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaResultados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('consecutivo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('resultado', models.CharField(default='', max_length=500)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('documento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
                ('id_TipoExamen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen')),
                ('id_examen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examenes')),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaExamenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('estado_folio', models.CharField(default='A', max_length=1)),
                ('documento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
                ('id_TipoExamen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen')),
                ('id_examen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examenes')),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(default='', max_length=250)),
                ('subjetivo', models.CharField(default='', max_length=250)),
                ('objetivo', models.CharField(default='', max_length=250)),
                ('analisis', models.CharField(default='', max_length=250)),
                ('plan', models.CharField(default='', max_length=250)),
                ('estado_folio', models.CharField(default='A', max_length=1)),
                ('documento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
                ('id_especialidad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades')),
                ('id_medico', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.medicos')),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
            ],
            options={
                'ordering': ['id_tipo_doc', 'documento', 'folio', 'fecha', 'id_especialidad', 'id_medico', 'motivo', 'subjetivo', 'objetivo', 'analisis', 'plan'],
            },
        ),
        migrations.AddField(
            model_name='examenes',
            name='id_TipoExamen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.CreateModel(
            name='EspecialidadesMedicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades')),
                ('id_medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.medicos')),
            ],
        ),
    ]
