# Generated by Django 3.2 on 2022-01-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('id_departamento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('id_ciudad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ciudades')),
                ('id_departamento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos')),
            ],
        ),
    ]
